// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVmAvVBoy5mDcfiPYhiJTrzxjFN_c7nwU',
    appId: '1:704109138893:web:024da7bc045c99df346a84',
    messagingSenderId: '704109138893',
    projectId: 'joanda0',
    authDomain: 'joanda0.firebaseapp.com',
    storageBucket: 'joanda0.appspot.com',
    measurementId: 'G-12TFYN15TM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2q5KypDQho3dpFAAQLL4-WbghaSHJGb4',
    appId: '1:704109138893:android:4d04346c3d0189f6346a84',
    messagingSenderId: '704109138893',
    projectId: 'joanda0',
    storageBucket: 'joanda0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFj_m_pOFHqjhcFUehzUNFmp-VSOnnekg',
    appId: '1:704109138893:ios:a09a275ac0f95bdb346a84',
    messagingSenderId: '704109138893',
    projectId: 'joanda0',
    storageBucket: 'joanda0.appspot.com',
    iosClientId: '704109138893-gijruqkpenoqpccig6lfb9t5q315hvar.apps.googleusercontent.com',
    iosBundleId: 'com.example.joanda0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFj_m_pOFHqjhcFUehzUNFmp-VSOnnekg',
    appId: '1:704109138893:ios:7ba9e56995c9390f346a84',
    messagingSenderId: '704109138893',
    projectId: 'joanda0',
    storageBucket: 'joanda0.appspot.com',
    iosClientId: '704109138893-ba21e6miloh8lo5rsd7cn8h3acalgd2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.joanda0.RunnerTests',
  );
}
